config/routes.rb
Rails.application.routes.draw do
  get 'ingestions/index'
  get 'static_pages/home'
  get 'sessions/new'
  root 'static_pages#home'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users
  resources :dishes
  resources :ingestions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
  has_many :dish_ingestions, dependent: :destroy
  has_many :ingestions, through: :dish_ingestions
  validates :name,  presence: true, length: { maximum: 100 }
  before_save { name.downcase! }
  validates :weight, presence: true, length: { maximum: 10 }
  validates :calorie_value, presence: true, length: { maximum: 10 }
  validates :proteins, presence: true, length: { maximum: 10 }
  validates :carbohydrates, presence: true, length: { maximum: 10 }
  validates :fats, presence: true, length: { maximum: 10 }
end

app/models/dish_ingestion.rb
class DishIngestion < ApplicationRecord
  belongs_to :dish, optional: true
  belongs_to :ingestion
end

app/models/ingestion.rb
class Ingestion < ApplicationRecord
  belongs_to :user, inverse_of: :ingestions
  has_many :dish_ingestions, dependent: :destroy
  has_many :dishes, through: :dish_ingestions
  validates :user_id, presence: true
  default_scope -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ingestions, inverse_of: :user, dependent: :destroy
  before_save { email.downcase! }
  validates :name,  presence: true, length: { maximum: 50 }
  validates :surname,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                        format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
  validates :age, presence: true, length: { maximum: 3 }
  validates :weight, presence: true, length: { maximum: 3 }
  validates :height, presence: true, length: { maximum: 3 }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :current_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @dishes = Dish.all
  end

  def show
    @dish = Dish.find(params[:id])
   end

  def new
    @dish = Dish.new
  end

  def create
  @dish = Dish.new(dish_params)
  if @dish.save
    flash[:success] = "Our dish is create!"
    redirect_to @dish
    else
      render 'new'
    end
  end

  def edit
    @dish = Dish.find(params[:id])
  end

  def update
    @dish = Dish.find(params[:id])
    if @dish.update_attributes(dish_params)
      flash[:success] = "Dish updated"
      redirect_to @dish
    else
      render 'edit'
    end
  end

  def destroy
    Dish.find(params[:id]).destroy
    flash[:success] = "Dish deleted."
    redirect_to dishes_url
  end

  private

  def dish_params
    params.require(:dish).permit(:name, :weight, :calorie_value, :proteins, :carbohydrates, :fats)
  end
end

app/controllers/ingestions_controller.rb
class IngestionsController < ApplicationController
  before_action :current_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:destroy]

  def index
    @ingestions = Ingestion.all
  end

  def show
    @ingestion = Ingestion.find(params[:id])
  end

  def new
    @ingestion = Ingestion.new
  end

  def create
    @ingestion = current_user.ingestions.new(ingestion_params)
    if @ingestion.save!
      flash[:success] = "Ingestion created!"
      render 'ingestions/index'
    else
      render 'static_pages/home'
    end
  end

  def edit
    @ingestion = Ingestion.find(params[:id])
  end

  def update
    @ingestion = Ingestion.find(params[:id])
    if @ingestion.update(ingestion_params)
      flash[:success] = "Ingestion updated"
      redirect_to @ingestion
    else
      render 'edit'
    end
  end

  def destroy
    Ingestion.find(params[:id]).destroy
    flash[:success] = "Ingestion deleted."
    redirect_to ingestions_url
  end

  private

  def ingestion_params
    defaults = { user_id: current_user.id }
    params.require(:ingestion).permit(:user_id, :dish_ids=>[])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :admin_user,     only: :destroy

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
  @user = User.new(user_params)
  if @user.save
    log_in @user
    flash[:success] = "Welcome!"
    redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :surname, :age, :weight, :height, :email, :password, :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Sport Fit"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/ingestions_helper.rb
module IngestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user?(user)
    user == current_user
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dishes/_footer.html.erb
<footer class="footer">
  <small>
    *Total carbohydrates
  </small>
</footer>

app/views/dishes/_form.html.erb
<%= form_for(@dish) do |f| %>
<%= render 'shared/error_messages_dishes' %>

<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %>

<%= f.label :weight %>
<%= f.text_field :weight, class: 'form-control' %>

<%= f.label :calorie_value %>
<%= f.text_field :calorie_value, class: 'form-control' %>

<%= f.label :proteins %>
<%= f.text_field :proteins, class: 'form-control' %>

<%= f.label :carbohydrates %>
<%= f.text_field :carbohydrates, class: 'form-control' %>

<%= f.label :fats %>
<%= f.text_field :fats, class: 'form-control' %>

<%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/dishes/edit.html.erb
<% provide(:title, 'Edit dish') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your dish</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/dishes/index.html.erb
<% provide(:title, 'All dishes') %>
<h1>All dishes</h1>

<table class="dishes">
  <thead>
    <tr>
      <th class="row-1 row-name">Name</th>
      <th class="row-2 row-weight">Weight</th>
      <th class="row-3 row-calorie_value">Calories</th>
      <th class="row-4 row-proteins">Proteins</th>
      <th class="row-5 row-carbohydrates">Carbs*</th>
      <th class="row-6 row-fats">Fats</th>
    </tr>
  </thead>

<% @dishes.each do |dish| %>
<tbody>
  <tr>
    <td><%= dish.name %></td>
    <td><%= dish.weight %></td>
    <td><%= dish.calorie_value %></td>
    <td><%= dish.proteins %></td>
    <td><%= dish.carbohydrates %></td>
    <td><%= dish.fats %></td>
    <td><%= link_to 'Edit', edit_dish_path(dish) %></td>
    <% if current_user.admin? %>
    <td><%= link_to 'Destroy', dish, method: :delete,
                                     data: { confirm: 'Are you sure?' } %></td>
                                     <% end %>
<% end %>
</tbody>
</table>

<br>
<%= link_to 'New Dish', new_dish_path %>
<%= render 'footer' %>

app/views/dishes/new.html.erb
<% provide(:title, 'Create dish') %>
<% provide(:button_text, 'Create a dish') %>
<h1>Choose our dish</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/dishes/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @dish.name %>
      </h1>
      <h1>
        <%= @dish.weight %>
      </h1>
      <h1>
        <%= @dish.calorie_value %>
      </h1>
      <h1>
        <%= @dish.proteins %>
      </h1>
      <h1>
        <%= @dish.carbohydrates %>
      </h1>
      <h1>
        <%= @dish.fats %>
      </h1>
    </section>
  </aside>
</div>

app/views/ingestions/_form.html.erb
<%= form_for(@ingestion) do |f| %>



<%= f.label :dish_id %>
<% Dish.all.each do |dish| %>
  <%= check_box_tag "ingestion[dish_ids][]", dish.id, @ingestion.dish_ids.include?(dish.id), id: dom_id(dish) %>
  <%= dish.name %><br/>
<% end %>


<%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/ingestions/edit.html.erb
<% provide(:title, 'Edit ingestion') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your ingestion</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/ingestions/index.html.erb
<%- provide(:title, 'Ingestions') %>
<h1>List of your ingestion</h1>
<table class="ingestions">
  <thead>
    <tr>
      <th class="row-1 row-name">Name</th>
      <th class="row-2 row-created_at">Date</th>
    </tr>
  </thead>
  <%- current_user.ingestions.each do |ingestion| %>
  <%- ingestion.dishes.each do |dish| %>
  <tbody>
    <tr>
      <td><%= dish.name %></td>
      <td><%= ingestion.created_at.to_date %></td>
      <td><%= link_to 'Edit', edit_ingestion_path(ingestion) %></td>
      <td><%= link_to 'Destroy', ingestion, method: :delete,
                                       data: { confirm: 'Are you sure?' } %></td>
  <% end %>
  <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Ingestion', new_ingestion_path %>

app/views/ingestions/new.html.erb
<% provide(:title, 'Create an ingestion') %>
<% provide(:button_text, 'Create an ingestion') %>
<h1>Create our ingestion</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/ingestions/show.html.erb
<% provide(:title, 'Show ingestion') %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info"
    <ul>
        <%- @ingestion.dishes.each do |dish| %>
        <h3> <%= dish.name %></h3>
        <% end %>
        <h2> Created at: <%= @ingestion.created_at %></h2>
        </ul>
    </section>
  </aside>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sport fit", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
        <li><%= link_to "Ingestion", ingestions_index_path %></li>
        <li><%= link_to "All users", users_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Dishes <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "All dishes", dishes_path %></li>
            <li><%= link_to "Create dish", new_dish_path %></li>
          </ul>
        </li>
        <li><%= link_to "Statistics", '#' %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: :delete %>
            </li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_dishes.html.erb
<% if @dish.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@dish.errors.count, "error") %>.
    </div>
    <ul>
    <% @dish.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sport Fit!</h1>

  <h2>
    This is the home page
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("sport.png", alt: "SportFit logo") %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages' %>

<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %>

<%= f.label :surname %>
<%= f.text_field :surname, class: 'form-control' %>

<%= f.label :age %>
<%= f.text_field :age, class: 'form-control' %>

<%= f.label :weight %>
<%= f.text_field :weight, class: 'form-control' %>

<%= f.label :height %>
<%= f.text_field :height, class: 'form-control' %>

<%= f.label :email %>
<%= f.email_field :email, class: 'form-control' %>

<%= f.label :password %>
<%= f.password_field :password, class: 'form-control' %>

<%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation, class: 'form-control' %>

<%= f.submit yield(:button_text), class: "btn btn-primary" %>

<% end %>

app/views/users/_user.html.erb
<li>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
       <%= link_to user.name, user %>
       <% if current_user.admin? %>
       <%= link_to 'Destroy', user, method: :delete,
                                        data: { confirm: 'Are you sure?' } %>
       <% end %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
       <%= @user.name %>
      </h1>
      <h1>
        <%= @user.surname %>
      </h1>
      <h1>
        <%= @user.age %>
      </h1>
    </section>
  </aside>
</div>